name: Build Java Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and test Java backend
      run: mvn -B package --file backend/pom.xml

    - name: Upload Java build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-build
        path: backend/target/*.jar
