name: Build and Deploy Nuxt Frontend (SPA)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Nuxt frontend (SPA)
        run: |
          cd frontend
          npm run build

      - name: List build directory (for debugging)
        run: |
          ls -la frontend/.output

      - name: Compress build artifacts
        run: |
          cd frontend
          tar -czf nuxt-build.tar.gz .output nuxt.config.ts package.json assets ecosystem.config.js

      - name: List compressed file (for debugging)
        run: |
          ls -la frontend/nuxt-build.tar.gz

      - name: Upload Nuxt build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-build
          path: frontend/nuxt-build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Nuxt build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuxt-build
          path: .

      - name: Deploy Nuxt frontend (SPA)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          scp -o StrictHostKeyChecking=no -i deploy_key nuxt-build.tar.gz ibm@123.207.71.173:/tmp/nuxt-build.tar.gz || { echo 'SCP failed'; exit 1; }
          ssh -o StrictHostKeyChecking=no -i deploy_key ibm@123.207.71.173 '
            export NVM_DIR="$HOME/.nvm" &&
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
            nvm use 16.20.2 &&
            sudo -E mkdir -p /usr/share/nginx/html/ibminscut && echo "success" &&
            sudo -E tar -xzf /tmp/nuxt-build.tar.gz -C /usr/share/nginx/html/ibminscut &&
            sudo -E chown -R www-data:www-data /usr/share/nginx/html/ibminscut &&
            sudo -E chmod -R 755 /usr/share/nginx/html/ibminscut &&
            rm /tmp/nuxt-build.tar.gz &&
            cd /usr/share/nginx/html/ibminscut &&
            sudo -E /home/ibm/.nvm/versions/node/v16.20.2/bin/npm install --production &&
            sudo -E env "PATH=$PATH" /home/ibm/.nvm/versions/node/v16.20.2/bin/pm2 start /usr/share/nginx/html/ibminscut/ecosystem.config.js
          ' || { echo 'SSH command failed'; exit 1; }
          rm deploy_key