name: Build and Deploy Vue Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Vue frontend
      run: npm run build

    - name: List build directory (for debugging)
      run: ls -la .output

    - name: Upload Vue build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vue-build
        include-hidden-files: true
        path: .output/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Vue build artifacts
      uses: actions/download-artifact@v3
      with:
        name: vue-build
        path: .output

    - name: List downloaded artifacts (for debugging)
      run: ls -la .output

    - name: Deploy Vue frontend
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        scp -o StrictHostKeyChecking=no -i deploy_key -r .output/* ibm@123.207.71.173:/usr/share/nginx/html/ibminscut
        rm deploy_key