name: Build and Deploy Vue Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Build Vue frontend
      run: |
        cd frontend
        npm run build

    - name: List build directory (for debugging)
      run: |
        ls -la frontend/.output

    - name: Compress build artifacts
      run: |
        cd frontend
        tar -czf vue-build.tar.gz .output

    - name: List compressed file (for debugging)
      run: |
        ls -la frontend/vue-build.tar.gz

    - name: Upload Vue build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vue-build
        path: frontend/vue-build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Vue build artifacts
      uses: actions/download-artifact@v3
      with:
        name: vue-build
        path: vue-build.tar.gz

    - name: Deploy Vue frontend
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "$SSH_PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        scp -o StrictHostKeyChecking=no -i deploy_key vue-build.tar.gz ibm@123.207.71.173:/tmp/vue-build.tar.gz || { echo 'SCP failed'; exit 1; }
        ssh -o StrictHostKeyChecking=no -i deploy_key ibm@123.207.71.173 'echo "$SSH_PASSWORD" | sudo -S mkdir -p /usr/share/nginx/html/ibminscut && echo "$SSH_PASSWORD" | sudo -S tar -xzf /tmp/vue-build.tar.gz -C /usr/share/nginx/html/ibminscut && echo "$SSH_PASSWORD" | sudo -S chown -R www-data:www-data /usr/share/nginx/html/ibminscut && echo "$SSH_PASSWORD" | sudo -S chmod -R 755 /usr/share/nginx/html/ibminscut && rm /tmp/vue-build.tar.gz' || { echo 'SSH command failed'; exit 1; }
        rm deploy_key