name: Build and Deploy Vue Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Vue frontend
      run: npm run build

    - name: List build directory (for debugging)
      run: ls -la .output

    - name: Compress build artifacts
      run: tar -czf vue-build.tar.gz .output

    - name: Upload Vue build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vue-build
        path: vue-build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Vue build artifacts
      uses: actions/download-artifact@v3
      with:
        name: vue-build
        path: vue-build.tar.gz

    - name: Decompress build artifacts
      run: tar -xzf vue-build.tar.gz

    - name: List decompressed artifacts (for debugging)
      run: ls -la .output

    - name: Deploy Vue frontend
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        ssh -o StrictHostKeyChecking=no -i deploy_key ibm@123.207.71.173 'sudo mkdir -p /usr/share/nginx/html/ibminscut && sudo chown -R ibm:ibm /usr/share/nginx/html/ibminscut' || { echo 'SSH command failed'; exit 1; }
        scp -o StrictHostKeyChecking=no -i deploy_key -r .output/* ibm@123.207.71.173:/usr/share/nginx/html/ibminscut || { echo 'SCP failed'; exit 1; }
        rm deploy_key